# Generated by Django 2.2.10 on 2020-02-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='about',
        ),
    ]
