# Generated by Django 2.2.10 on 2020-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_auto_20200204_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=2083)),
                ('email', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
